### **SQL Basics**
Structured Query Language (SQL) is the standard language for managing and manipulating relational databases. It enables users to perform tasks such as querying data, updating records, and managing database structures. Understanding SQL is essential for anyone working with databases, as it provides a powerful and efficient way to interact with data.

Key Concepts:

- Database: A collection of organized data stored and accessed electronically.
- Table: A set of data elements organized in rows and columns within a database.
- Query: A request for data or information from a database.
- Primary Key: A unique identifier for a record in a table.
- Foreign Key: A field in one table that uniquely identifies a row of another table.

SQL allows for querying and modifying data, as well as performing various operations like filtering, sorting, and grouping.

Common SQL Commands:
- SELECT: Retrieve data from one or more tables.
- INSERT: Add new records into a table.
- UPDATE: Modify existing records.
- DELETE: Remove records from a table.
- JOIN: Combine rows from two or more tables based on a related column.

In [ ]:
"""
Objective: Create a new database named 'Company' and a table 'Employees' with columns for ID, Name, and Department.
"""
import sqlite3

# Connect to the database (or create it if it doesn't exist)
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Create the 'Employees' table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS Employees (
        ID INTEGER PRIMARY KEY,
        Name TEXT NOT NULL,
        Department TEXT NOT NULL
    )
''')

# Commit the changes and close the connection
conn.commit()
conn.close()

# TODO: Add error handling to manage potential exceptions during database operations.

In [ ]:
"""
Objective: Insert sample employee records into the 'Employees' table.
"""
import sqlite3

# Connect to the database
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Insert sample records
employees = [
    (1, 'Alice Johnson', 'HR'),
    (2, 'Bob Smith', 'Engineering'),
    (3, 'Charlie Davis', 'Marketing')
]

cursor.executemany('''
    INSERT INTO Employees (ID, Name, Department)
    VALUES (?, ?, ?)
''', employees)

# Commit the changes and close the connection
conn.commit()
conn.close()

# TODO: Implement a function to insert a new employee record with user input.

In [ ]:
"""
Objective: Retrieve and display all employee records from the 'Employees' table.
"""
import sqlite3

# Connect to the database
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Retrieve all records
cursor.execute('SELECT * FROM Employees')
rows = cursor.fetchall()

# Display the records
for row in rows:
    print(row)

# Close the connection
conn.close()

# TODO: Modify the query to retrieve employees from a specific department.

In [ ]:
"""
Objective: Update the department of an employee in the 'Employees' table.
"""
import sqlite3

# Connect to the database
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Update the department for employee with ID 2
cursor.execute('''
    UPDATE Employees
    SET Department = ?
    WHERE ID = ?
''', ('Sales', 2))

# Commit the changes and close the connection
conn.commit()
conn.close()

# TODO: Implement a function to update an employee's department based on user input.

In [ ]:
"""
Objective: Delete an employee record from the 'Employees' table.
"""
import sqlite3

# Connect to the database
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Delete the employee with ID 3
cursor.execute('''
    DELETE FROM Employees
    WHERE ID = ?
''', (3,))

# Commit the changes and close the connection
conn.commit()
conn.close()

# TODO: Implement a function to delete an employee record based on user input.

In [ ]:
"""
Objective: Delete an employee record from the 'Employees' table.
"""
import sqlite3

# Connect to the database
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Delete the employee with ID 3
cursor.execute('''
    DELETE FROM Employees
    WHERE ID = ?
''', (3,))

# Commit the changes and close the connection
conn.commit()
conn.close()

# TODO: Implement a function to delete an employee record based on user input.

In [ ]:
"""
Objective: Retrieve and display employee records along with their department names using a JOIN operation.
"""
import sqlite3

# Connect to the database
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Create a 'Departments' table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS Departments (
        DepartmentID INTEGER PRIMARY KEY,
        DepartmentName TEXT NOT NULL
    )
''')

# Insert sample department records
departments = [
    (1, 'HR'),
    (2, 'Engineering'),
    (3, 'Marketing'),
    (4, 'Sales')
]

cursor.executemany('''
    INSERT INTO Departments (DepartmentID, DepartmentName)
    VALUES (?, ?)
''', departments)

# Create a 'DepartmentAssignments' table to link employees to departments
cursor.execute('''
    CREATE TABLE IF NOT EXISTS DepartmentAssignments (
        EmployeeID INTEGER,
        DepartmentID INTEGER,
        FOREIGN KEY (EmployeeID) REFERENCES Employees(ID),
        FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID)
    )
''')

# Assign employees to departments
assignments = [
    (1, 1),  # Alice Johnson to HR
    (2, 2),  # Bob Smith to Engineering
    (4, 4)   # Charlie Davis to Sales
]

cursor.executemany('''
    INSERT INTO DepartmentAssignments (EmployeeID, DepartmentID)
    VALUES (?, ?)
''', assignments)

# Retrieve employee names along with their department names
cursor.execute('''
    SELECT Employees.Name, Departments.DepartmentName
    FROM Employees
    JOIN DepartmentAssignments ON Employees.ID = DepartmentAssignments.EmployeeID
    JOIN Departments ON DepartmentAssignments.DepartmentID = Departments.DepartmentID
''')
rows = cursor.fetchall()

# Display the records
for row in rows:
    print(row)

# Commit the changes and close the connection
conn.commit()
conn.close()

# TODO: Modify the query to include employees who are not assigned to any department.

In [ ]:
"""
Objective: Calculate and display the total number of employees in each department.
"""
import sqlite3

# Connect to the database
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Retrieve the count of employees in each department
cursor.execute('''
    SELECT Departments.DepartmentName, COUNT(Employees.ID) AS EmployeeCount
    FROM Departments
    LEFT JOIN DepartmentAssignments ON Departments.DepartmentID = DepartmentAssignments.DepartmentID
    LEFT JOIN Employees ON DepartmentAssignments.EmployeeID = Employees.ID
    GROUP BY Departments.DepartmentName
''')
rows = cursor.fetchall()

# Display the records
for row in rows:
    print(f"Department: {row[0]}, Employee Count: {row[1]}")

# Close the connection
conn.close()

# TODO: Modify the query to include departments with zero employees.

In [ ]:
"""
Objective: Retrieve and display the names of employees working in the department with the most employees.
"""
import sqlite3

# Connect to the database
conn = sqlite3.connect('Company.db')
cursor = conn.cursor()

# Retrieve the department with the most employees
cursor.execute('''
    SELECT DepartmentName
    FROM Departments
    WHERE DepartmentID = (
        SELECT DepartmentID
        FROM DepartmentAssignments
        GROUP BY DepartmentID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
''')
department_name = cursor.fetchone()[0]

# Retrieve employee names from the department with the most employees
cursor.execute('''
    SELECT Employees.Name
    FROM Employees
    JOIN DepartmentAssignments ON Employees.ID = DepartmentAssignments.EmployeeID
    JOIN Departments ON DepartmentAssignments.DepartmentID = Departments.DepartmentID
    WHERE Departments.DepartmentName = ?
''', (department_name,))
rows = cursor.fetchall()

# Display the records
print(f"Employees in the department with the most employees ({department_name}):")
for row in rows:
    print(row[0])

# Commit the changes and close the connection
conn.commit()
conn.close()

# TODO: Modify the query to also include the number of employees in the department.

### **Reflection**
In your opinion, which SQL operation (such as querying data, using joins, or applying aggregate functions) do you think is the most important when working with databases, and why?

(answer here)

### **Exploration**
Although SQL is powerful, it’s worth exploring NoSQL databases (like MongoDB and Cassandra), which offer a different way to structure and access data, especially for unstructured data or high-volume use cases.

For more advanced SQL practice please refer to https://www.hackerrank.com/domains/sql